In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# read csv
house = pd.read_csv(r'D:\data set\HousePrices.csv')
house

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
#head()
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
#tail()
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
#info()
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
house.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [7]:
#drop id column
house.drop('Id', axis =1, inplace = True)

In [9]:
house.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [10]:
house.isnull().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [11]:
#dropping columns having more null values ['Alley']['FireplaceQu']['PoolQC']['Fence']['MiscFeature']
house.drop(['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'], axis =1, inplace = True)

In [12]:
house.shape

(1460, 75)

In [13]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(34), object(38)
memory usage: 855.6+ KB

In [14]:
house.dropna(axis=0, how = 'any', inplace = True)

In [15]:
house

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [16]:
house.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 75 columns):
MSSubClass       1094 non-null int64
MSZoning         1094 non-null object
LotFrontage      1094 non-null float64
LotArea          1094 non-null int64
Street           1094 non-null object
LotShape         1094 non-null object
LandContour      1094 non-null object
Utilities        1094 non-null object
LotConfig        1094 non-null object
LandSlope        1094 non-null object
Neighborhood     1094 non-null object
Condition1       1094 non-null object
Condition2       1094 non-null object
BldgType         1094 non-null object
HouseStyle       1094 non-null object
OverallQual      1094 non-null int64
OverallCond      1094 non-null int64
YearBuilt        1094 non-null int64
YearRemodAdd     1094 non-null int64
RoofStyle        1094 non-null object
RoofMatl         1094 non-null object
Exterior1st      1094 non-null object
Exterior2nd      1094 non-null object
MasVnrType       1094 non-null object
MasVnrArea       1094 non-null float64
ExterQual        1094 non-null object
ExterCond        1094 non-null object
Foundation       1094 non-null object
BsmtQual         1094 non-null object
BsmtCond         1094 non-null object
BsmtExposure     1094 non-null object
BsmtFinType1     1094 non-null object
BsmtFinSF1       1094 non-null int64
BsmtFinType2     1094 non-null object
BsmtFinSF2       1094 non-null int64
BsmtUnfSF        1094 non-null int64
TotalBsmtSF      1094 non-null int64
Heating          1094 non-null object
HeatingQC        1094 non-null object
CentralAir       1094 non-null object
Electrical       1094 non-null object
1stFlrSF         1094 non-null int64
2ndFlrSF         1094 non-null int64
LowQualFinSF     1094 non-null int64
GrLivArea        1094 non-null int64
BsmtFullBath     1094 non-null int64
BsmtHalfBath     1094 non-null int64
FullBath         1094 non-null int64
HalfBath         1094 non-null int64
BedroomAbvGr     1094 non-null int64
KitchenAbvGr     1094 non-null int64
KitchenQual      1094 non-null object
TotRmsAbvGrd     1094 non-null int64
Functional       1094 non-null object
Fireplaces       1094 non-null int64
GarageType       1094 non-null object
GarageYrBlt      1094 non-null float64
GarageFinish     1094 non-null object
GarageCars       1094 non-null int64
GarageArea       1094 non-null int64
GarageQual       1094 non-null object
GarageCond       1094 non-null object
PavedDrive       1094 non-null object
WoodDeckSF       1094 non-null int64
OpenPorchSF      1094 non-null int64
EnclosedPorch    1094 non-null int64
3SsnPorch        1094 non-null int64
ScreenPorch      1094 non-null int64
PoolArea         1094 non-null int64
MiscVal          1094 non-null int64
MoSold           1094 non-null int64
YrSold           1094 non-null int64
SaleType         1094 non-null object
SaleCondition    1094 non-null object
SalePrice        1094 non-null int64
dtypes: float64(3), int64(34), object(38)
memory usage: 649.6+ KB

In [17]:
#First, find out all the features with type object in the test data:
objList = house.select_dtypes(include = 'object').columns
print(objList)

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
       'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')

In [18]:
#label encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for feat in objList:
    house[feat] = le.fit_transform(house[feat].astype(str))
print(house.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 75 columns):
MSSubClass       1094 non-null int64
MSZoning         1094 non-null int32
LotFrontage      1094 non-null float64
LotArea          1094 non-null int64
Street           1094 non-null int32
LotShape         1094 non-null int32
LandContour      1094 non-null int32
Utilities        1094 non-null int32
LotConfig        1094 non-null int32
LandSlope        1094 non-null int32
Neighborhood     1094 non-null int32
Condition1       1094 non-null int32
Condition2       1094 non-null int32
BldgType         1094 non-null int32
HouseStyle       1094 non-null int32
OverallQual      1094 non-null int64
OverallCond      1094 non-null int64
YearBuilt        1094 non-null int64
YearRemodAdd     1094 non-null int64
RoofStyle        1094 non-null int32
RoofMatl         1094 non-null int32
Exterior1st      1094 non-null int32
Exterior2nd      1094 non-null int32
MasVnrType       1094 non-null int32
MasVnrArea       1094 non-null float64
ExterQual        1094 non-null int32
ExterCond        1094 non-null int32
Foundation       1094 non-null int32
BsmtQual         1094 non-null int32
BsmtCond         1094 non-null int32
BsmtExposure     1094 non-null int32
BsmtFinType1     1094 non-null int32
BsmtFinSF1       1094 non-null int64
BsmtFinType2     1094 non-null int32
BsmtFinSF2       1094 non-null int64
BsmtUnfSF        1094 non-null int64
TotalBsmtSF      1094 non-null int64
Heating          1094 non-null int32
HeatingQC        1094 non-null int32
CentralAir       1094 non-null int32
Electrical       1094 non-null int32
1stFlrSF         1094 non-null int64
2ndFlrSF         1094 non-null int64
LowQualFinSF     1094 non-null int64
GrLivArea        1094 non-null int64
BsmtFullBath     1094 non-null int64
BsmtHalfBath     1094 non-null int64
FullBath         1094 non-null int64
HalfBath         1094 non-null int64
BedroomAbvGr     1094 non-null int64
KitchenAbvGr     1094 non-null int64
KitchenQual      1094 non-null int32
TotRmsAbvGrd     1094 non-null int64
Functional       1094 non-null int32
Fireplaces       1094 non-null int64
GarageType       1094 non-null int32
GarageYrBlt      1094 non-null float64
GarageFinish     1094 non-null int32
GarageCars       1094 non-null int64
GarageArea       1094 non-null int64
GarageQual       1094 non-null int32
GarageCond       1094 non-null int32
PavedDrive       1094 non-null int32
WoodDeckSF       1094 non-null int64
OpenPorchSF      1094 non-null int64
EnclosedPorch    1094 non-null int64
3SsnPorch        1094 non-null int64
ScreenPorch      1094 non-null int64
PoolArea         1094 non-null int64
MiscVal          1094 non-null int64
MoSold           1094 non-null int64
YrSold           1094 non-null int64
SaleType         1094 non-null int32
SaleCondition    1094 non-null int32
SalePrice        1094 non-null int64
dtypes: float64(3), int32(38), int64(34)
memory usage: 487.2 KB
None

In [19]:
house

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,3,65.0,8450,1,3,3,0,4,0,...,0,0,0,0,0,2,2008,8,4,208500
1,20,3,80.0,9600,1,3,3,0,2,0,...,0,0,0,0,0,5,2007,8,4,181500
2,60,3,68.0,11250,1,0,3,0,4,0,...,0,0,0,0,0,9,2008,8,4,223500
3,70,3,60.0,9550,1,0,3,0,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,60,3,84.0,14260,1,0,3,0,2,0,...,0,0,0,0,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,62.0,7917,1,3,3,0,4,0,...,0,0,0,0,0,8,2007,8,4,175000
1456,20,3,85.0,13175,1,3,3,0,4,0,...,0,0,0,0,0,2,2010,8,4,210000
1457,70,3,66.0,9042,1,3,3,0,4,0,...,0,0,0,0,2500,5,2010,8,4,266500
1458,20,3,68.0,9717,1,3,3,0,4,0,...,112,0,0,0,0,4,2010,8,4,142125
1459,20,3,75.0,9937,1,3,3,0,4,0,...,0,0,0,0,0,6,2008,8,4,147500

In [20]:
y = house.iloc[:,-1]
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1094, dtype: int64

In [21]:
X = house.iloc[:,0:74]
X

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,3,65.0,8450,1,3,3,0,4,0,...,61,0,0,0,0,0,2,2008,8,4
1,20,3,80.0,9600,1,3,3,0,2,0,...,0,0,0,0,0,0,5,2007,8,4
2,60,3,68.0,11250,1,0,3,0,4,0,...,42,0,0,0,0,0,9,2008,8,4
3,70,3,60.0,9550,1,0,3,0,0,0,...,35,272,0,0,0,0,2,2006,8,0
4,60,3,84.0,14260,1,0,3,0,2,0,...,84,0,0,0,0,0,12,2008,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,62.0,7917,1,3,3,0,4,0,...,40,0,0,0,0,0,8,2007,8,4
1456,20,3,85.0,13175,1,3,3,0,4,0,...,0,0,0,0,0,0,2,2010,8,4
1457,70,3,66.0,9042,1,3,3,0,4,0,...,60,0,0,0,0,2500,5,2010,8,4
1458,20,3,68.0,9717,1,3,3,0,4,0,...,0,112,0,0,0,0,4,2010,8,4
1459,20,3,75.0,9937,1,3,3,0,4,0,...,68,0,0,0,0,0,6,2008,8,4

In [22]:
y = house.iloc[:,-1]
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1094, dtype: int64

In [39]:
#test train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.80, random_state = 100)
y_test.shape

(219,)

In [40]:
X_test.shape

(219, 74)

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
regressor = LinearRegression()

In [43]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
y_pred = regressor.predict(X_test)
y_pred

array([161803.77216327, 104330.69176961, 177926.91788344, 123475.89317638,
       245152.79284677, 357625.16000827, 143119.26159683, 202909.00316941,
       181055.85919399, 176956.1673478 , 125444.52883116, 117084.73721207,
       138035.10370642, 179980.66034477, 188379.75880093, 146270.78018982,
        86625.76833763, 125117.48378266, 111196.18240833,  72342.2813498 ,
       251895.79484763, 105757.36519033, 122367.48883865, 226376.25940493,
        73510.33044121, 297722.19641483, 279012.31342619, 178088.09610101,
        91180.43196568, 168068.57167324, 212787.95160177, 180543.76288582,
       352577.10323352,  87689.05405767, 182340.2870864 ,  73131.38954012,
       102142.41548949, 162807.83687422, 245323.5352821 , 127706.6319197 ,
       235405.33596185, 115265.98577933, 159340.75248987, 297344.36710594,
       320321.2075802 , 187238.48658414, 158166.66813957, 108552.65846084,
        93374.10717275, 167071.150056  , 221441.26599909, 129599.15109555,
       143653.38885153, 124937.98634535, 284380.72120479, 120378.6409869 ,
       129420.73921992, 117217.21534975, 217934.24268828, 132062.78334378,
       160002.03487166, 312520.94423219, 109294.68943144, 389497.19590838,
       145825.07124158, 123357.92847418, 190874.90072895, 116730.86000381,
       109754.22421445, 242933.55252722, 291758.08339821, 110471.29847232,
       140005.65964331, 158894.70042815, 266523.46194018, 177740.64420816,
       127753.0144171 , 162435.27397726, 180320.3493601 , 312434.84881592,
       122743.74390961, 102586.38574871, 297317.81164011, 207566.9210359 ,
       157711.19270922, 134716.0871683 , 248630.62000618, 194381.08676149,
        98540.25190525, 219211.49902525, 190887.6582856 ,  81948.91361896,
       228303.87578745, 255995.96407018, 207607.44074412, 155429.89209445,
       102552.95351725, 292595.60673367, 195276.80262346, 277071.93882182,
       367897.55939639, 219209.39347767, 134617.15437743, 224312.79518799,
       313828.92445288, 191531.52933978, 575057.02065363, 282005.8971164 ,
       148307.09008614, 118623.28761096, 129945.01705837, 275384.86532035,
       130767.46715629, 175723.34827715, 353646.49214598, 174347.47415861,
        82969.09457468, 217058.73478041, 133091.66760636, 268920.83904256,
       302888.69846458, 123864.35364175,  81870.97015839, 232796.98302633,
       107217.04749364,  63603.50548466, 144305.01111203, 216044.5174318 ,
       126978.43684655, 144048.01863967, 166102.53429042, 325655.73819932,
       193071.84729416, 155361.67060223, 204273.67025689,  88164.08739315,
       385718.86399666, 203170.44307355, 243455.45993032,  99731.47943301,
       127560.03495921, 117971.93220389, 198439.47794929, 344669.97218246,
       150712.3416356 , 120377.96005234, 115864.59552247, 121020.85058547,
       238747.62593114,  38395.31566428, 254653.92845732, 190795.13886945,
       133919.77809634, 208991.61495017, 144486.98951146, 249494.25659787,
        44188.64421757, 105330.59071632, 162955.07422069, 393621.18262589,
       217962.09800488,  86672.26552003, 221701.1703144 , 137076.32681289,
       283850.99626216, 110640.95135176, 291341.91642784, 419515.31250276,
       304550.31613652, 113463.2179936 , 221195.78865524, 108157.5275929 ,
       257321.71784923,  65710.51401823, 117121.512219  , 155344.71143116,
       216595.06513164, 189548.28435583, 222893.12631991, 129178.85238194,
       203302.73581482, 168213.5724273 , 300749.75664123, 425767.26551954,
       128651.78191796, 115141.35968242,  77936.04475922, 149988.78700356,
       127190.6511246 , 207064.74800916,  59277.482635  , 367960.72753006,
       151534.09262414, 170787.07925071, 136812.1907889 , 122598.55585719,
        85225.78711141, 141325.84232295, 179134.35312826, 190176.82964093,
       138453.81897411, 133837.24027714, 138215.99984382, 152933.13060651,
       262858.12495415, 116260.06971108, 304750.25367483, 197753.5740946 ,
       232739.33970485, 109151.25063092, 324780.41895447, 216547.0556045 ,
       195984.30681776, 109722.58325359, 169419.71172912, 163867.21065436,
       332853.38501134, 124551.71789919, 396148.60896368])

In [45]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

1439371648.1323726

In [46]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8034256156172703